import os

BUCKET_NAME = os.getenv("BUCKET_NAME")
AWS_S3_REGION = os.getenv("AWS_S3_REGION", "us-east-1")
AWS_SERVICE_ACCOUNT_ACCESS_KEY = os.getenv("AWS_SERVICE_ACCOUNT_S3_ACCESS_KEY")
AWS_SERVICE_ACCOUNT_ACCESS_SECRET = os.getenv("AWS_SERVICE_ACCOUNT_S3_ACCESS_SECRET")

AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN")
AUTH0_ACCESS_TOKEN = os.getenv("AUTH0_ACCESS_TOKEN")
ALL_APPLICATIONS_CLIENT_ID = os.getenv("ALL_APPLICATIONS_CLIENT_ID")
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS")
